-- 1 Pull total number of orders that were completed on 18th March 2023
SELECT COUNT(*) AS total_orders
FROM sale
WHERE date = '2023-03-18';

--2 Pull total number of orders completed on 18th March 2023 with the first name 'John' and last name 'Doe'
SELECT COUNT(*) AS total_orders
FROM sale s
JOIN customer c ON s.customer_id = c.customer_id
WHERE s.date = '2023-03-18'
AND c.first_name = 'John'
AND c.last_name = 'Doe';

--3  Pull total number of customers that purchased in January 2023 and the average amount spend per customer
SELECT 
    COUNT(DISTINCT customer_id) AS total_customers,
    ROUND(AVG(total_spend), 2) AS avg_spend_per_customer
FROM (
    SELECT 
        customer_id,
        SUM(revenue) AS total_spend
    FROM sale
    WHERE date >= '2023-01-01' AND date <= '2023-01-31'
    GROUP BY customer_id
) AS customer_spending;

-- 4  Pull the departments that generated less than $600 in 2022
SELECT 
    i.department,
    ROUND(SUM(s.revenue), 2) AS total_revenue
FROM sale s
JOIN item i ON s.item_id = i.item_id
WHERE s.date >= '2022-01-01' AND s.date <= '2022-12-31'
GROUP BY i.department
HAVING SUM(s.revenue) < 600
ORDER BY total_revenue DESC;

-- 5 what is the most and least revenue we have generated by an order
SELECT
    MAX(revenue) AS highest_revenue,
    MIN(revenue) AS lowest_revenue
FROM sale;


-- 6 What were the orders that were purchased in our most lucrative order
SELECT 
    s.order_id,
    s.date,
    c.first_name,
    c.last_name,
    i.item_name,
    s.quantity,
    s.revenue
FROM sale s
JOIN customer c ON s.customer_id = c.customer_id
JOIN item i ON s.item_id = i.item_id
WHERE s.revenue = (SELECT MAX(revenue) FROM sale)
ORDER BY s.date;


